# Tech Extension
:toc:

## Summary

* Issues:
** https://github.com/syndesisio/syndesis-project/issues/125
* Sprint: 19
* Affected Repos:
** syndesis-rest
** syndesis-ui
** syndesis-verifier
** syndesis-integration-runtime

## Objective

An expert user should be able to contribute additional steps using a binary archive that should be deployed to Syndesis via the UI.

## Archive format

The archive should be packages using `spring-boot-maven-plugin` using `MODULE` layout that bundles dependencies excluding those with `provided` scope and project resources (does not bundle bootstrap loader).

[source,xml]
.Example Usage
----
<plugin>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-maven-plugin</artifactId>
  <configuration>
    <layout>MODULE</layout>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>repackage</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

[WARNING]
====
Artifacts already provided by the integration should have *provided* as scope.
====

### Metadata

The archive is bundled with an `Extension Metada` that should be placed in

[source]
----
META-INF/syndesis/extension.json
----

And should contains:

[source,json]
----
{
  "kind": "extension",
  "data": {
    "id": "${groupId}:${artifactId}",
    "version": "${version}",
    "name": "Extension Name",
    "description": "Extension Description",
    "icon": "fa-puzzle-piece",
    "tags": [],
    "action": [
      {
        "id": "${actionId}",
        "name": "Action Name",
        "actionType" : "extension",
        "description": "Action Description",
        "tags": [],
        "definition": {
          "inputDataShape": {
           "kind" : "any"
         },
         "outputDataShape": {
           "kind" : "any"
         },
         "descriptor": {
             "target" : "route"
         },
         "propertyDefinitionSteps": []
       }
     }
   ]
  },
  "dependencies": [
      "mvn:g/a/v",
      "..."
  ]
}
----

[NOTE]
====
Extensions do not have global options.
====

== Storage

The extension are persisted on Syndesis backend using a `filestore` that should support file-system like paths and operation and should have a pluggable storage backend.


[source,java]
.FileStore interface
----
public interface FileStore {

    /**
     * Initialize the file store.
     */
    void init();

    /**
     * Write a file on a path.
     *
     * The path must be absolute (e.g. "/path/to/file.zip").
     *
     * If a file already exists it is overwritten.
     * Parent directories are created automatically.
     *
     * @param path the destination path
     * @param file the content of the file
     */
    void write(String path, InputStream file);

    /**
     * Write a file on a temporary path.
     *
     * The path wil be decided by the file store and returned to the client.
     *
     * @param file the content of the file
     * @return the path created for the file
     */
    String writeTemporaryFile(InputStream file);

    /**
     * Read a file from a path.
     *
     * The path must be absolute (e.g. "/path/to/file.zip").
     *
     * @param path the path to read
     * @return the file content or null if the file is not present
     */
    InputStream read(String path);

    /**
     * Delete a file corresponding to a path.
     *
     * The path must be absolute (e.g. "/path/to/file.zip").
     *
     * @param path the path to the file to delete
     * @return true if the file existed before deleting
     */
    boolean delete(String path);

    /**
     * Moves a file from a source path to a destination path.
     *
     * Both paths must be absolute (e.g. "/path/to/file.zip").
     *
     * If a file already exists in the destination path, it is overwritten.
     * If the source file does not exist, the operation is cancelled and the
     * destination file (if present) is left unchanged.
     *
     * @param fromPath the source path
     * @param toPath the destination path
     * @return true if the source file existed before moving it
     */
    boolean move(String fromPath, String toPath);

}
----

=== Default Implementation

The default `FileStore` implementation stores the extension (jar) in a DB table named "filestore" inside the `syndesis` database (PostgreSQL).

References:

* PR: https://github.com/syndesisio/syndesis-rest/pull/743
